# Generated by Django 4.1.2 on 2023-11-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_article_options_comment_articlecountview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecountview',
            name='session_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
